name: IBL frontend pipeline

on:
  push:
    branches: [test]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test Branch
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build react app
        run: npm run build

      - name: Quick Check
        run: ls -all

      - name: Upload React App to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.TEST_SERVER_IP_ADDRESS }}
          username: ${{ vars.TEST_SERVER_USERNAME }}
          key: ${{ secrets.TEST_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/"
          target: "."

      - name: Deploy React App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.TEST_SERVER_IP_ADDRESS }}
          username: ${{ vars.TEST_SERVER_USERNAME }}
          key: ${{ secrets.TEST_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            mv dist ibl
            sudo rm -r /var/www/html/*
            sudo cp -r ibl/* /var/www/html/
            sudo rm -r ibl
